# <!-- Powered by BMADâ„¢ Core -->
markdownExploder: true
qa:
  qaLocation: bmad-docs/qa
prd:
  prdFile: bmad-docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: bmad-docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: bmad-docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: bmad-docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - bmad-docs/architecture/coding-standards.md
  - bmad-docs/architecture/tech-stack.md
  - bmad-docs/architecture/project-structure.md
  - bmad-docs/architecture/git-workflow.md
devDebugLog: .ai/debug-log.md
devStoryLocation:
  - bmad-docs/stories
  - bmad-docs/impl-plan
slashPrefix: BMad
